- name : Configure Docker on EC2 Instances
  hosts : all
  become: false
  connection : ssh
  tasks :
  - name: updating yum
    command : sudo yum update -y

  - name : Install Docker
    command : sudo yum  install -y docker
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root

  - name: Deploy Docker Container
    command: sudo docker run -itd -p 9901:8081 nagaraju18/insure_me_nagu:46.0
